### ISSUE TITLE
Add an automation to run the tests

### ISSUE THREAD

**Issue by ajiyakin** [AccelByte/go-restful-plugins#3]
This would be helpful for us checking the tests before we actually merge it into master branch. Maybe we can use [Travis CI](https://travis-ci.org) for this since it has widely used by many of open-source project. So we need an account for the Travis CI then if we decided to use it.
What do you think @anggorodewanto ?

**Comment by anggorodewanto** [comment]
Yeah, why not, let me look at Travis

**Comment by anggorodewanto** [comment]
fixed with #4
